/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ads.poo;

public class App {
    public static void main(String[] args) {
        Buzz buzz1 = new Buzz();
        Buzz buzz2 = new Buzz();
        Buzz buzz3 = new Buzz();

        System.out.println("Buzz 1 diz: " + buzz1.falar());
        
        System.out.println("Buzz 2 diz: " + buzz2.falar());
                
        System.out.println("Buzz 3 diz: " + buzz3.falar());

        buzz1.botaoCapacete();
        
        if (buzz1.isEstadoCapacete()) System.out.println("Capacete do buzz 1 está aberto!");
        else System.out.println("Capacete do buzz 1 está fechado!");
        
        boolean aux = buzz2.botaoAsas();
        if (aux) System.out.println("Asa do buzz 2 está aberto!");
        else System.out.println("Asa do buzz 2 está fechado!");

        System.out.printf("Valor do dano causado pelo Laser do Buzz 1: %.2f\n", buzz1.dispararLaser());
        System.out.printf("Valor do dano causado pelo Golpe do Buzz 3: %.2f\n", buzz3.golpear());

    }
}
