/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ads.poo;

public class App {
    public static void main(String[] args) {
        Caneta caneta = new Caneta("Preta");

        System.out.println(caneta.desenhar());
    }
}
